### PR TITLE
fix beautylog dependency by removing it

### PR DESCRIPTION
**Pull request by philkunz**

### CODE REVIEW

**Comment by yanivefraim** [comment]
+1 please

**Comment by napalm684** [comment]
This going to be merged anytime soon?  Thanks!

**Comment by philkunz** [comment]
@napalm684 if this isn't fast enough for you, fork it and publish your own module. All the typings devs have real jobs too.

**Comment by napalm684** [comment]
Phil this was not intended to be a rude comment.  I was looking for an ETA for my team.  We all have jobs and I am fully aware of that, just trying to do mine.

**Comment by blakeembrey** [comment]
Sorry for the delay, I just landed back in Australia after a 24 hour flight. You can always install from GitHub. I have just given @philkunz access on GitHub, but I think I'll still have to publish to NPM after the transfer to @typings occurred.

**Comment by napalm684** [comment]
Thanks @blakeemery appreciate the quick turnaround

**Comment by philkunz** [comment]
@blakeembrey true, I removed myself on NPM, but I can take care of gulp-typings if you want me to.

**Comment by blakeembrey** [comment]
@philkunz I just added you back on NPM. I'm happy to help maintain the module, but any issues this week are best taken care of by you since I have a ton of things to catch up on. The module scope is quiet small, so I believe I won't have any trouble next week 😄

**Comment by philkunz** [comment]
@blakeembrey true. :)
@napalm684 does 2.0.1 on npm fix your problem?

**Comment by napalm684** [comment]
Hi @philkunz I tested this out this morning and seem to be having the same issue but with a different require (my node version is 5.5.0) (sorry for duplicate post had this in the issue):

```
Failed to run "C:\xxxx\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:\xxxx\node_modules\gulp-typings\dist\index.js:3
const plugins = require("./gulp-typings.plugins");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\xxxx\gulpfile.js:15:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by philkunz** [comment]
Ah I see the issue. My npmts module doesn't parse the target correctly. I'll fix it quickly.

**Comment by napalm684** [comment]
Thanks I figured it was a transpilation issue!

**Comment by philkunz** [comment]
Ok, fixed. See version 2.0.2 on npm

**Comment by napalm684** [comment]
@philkunz Another new one is this related?

```
Failed to run "C:\xxxx\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
Error: Cannot find module 'typings-global'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\xxxx\node_modules\gulp-typings\dist\gulp-typings.plugins.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\xxxx\node_modules\gulp-typings\dist\index.js:2:15)
```

**Comment by philkunz** [comment]
@napalm684  oh boy, today is not my day.
check version 2.0.3 on npm

**Comment by napalm684** [comment]
@philkunz Back in business sir can't thank you enough!  Well done!

**Comment by philkunz** [comment]
@napalm684 not for that, fixing one problem and creating another. I hate that... I'll improve my checks tooling to avoid this in the future. I'm currently working on [npmdocker](https://gitlab.com/pushrocks/npmdocker) which will be able to mount the directory and test different node versions all in docker locally before comitting or publishing anything... Again, sorry for the confusion.

**Comment by napalm684** [comment]
No problem @philkunz just appreciate the help in getting this resolved so quickly my team and I appreciate it.

**Comment by dangler** [comment]
Thanks @philkunz

**Pull request merged**
